# Generated by Django 4.2.3 on 2023-07-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.contract'),
            preserve_default=False,
        ),
    ]
